/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppPlatformRouteImport } from './routes/_app.platform'
import { Route as AppPlatformIndexRouteImport } from './routes/_app.platform.index'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app.workspace.$workspaceId'
import { Route as AppPlatformUsersRouteImport } from './routes/_app.platform.users'
import { Route as AppPlatformSettingsRouteImport } from './routes/_app.platform.settings'
import { Route as AppPlatformRolesRouteImport } from './routes/_app.platform.roles'
import { Route as AppPlatformClientsRouteImport } from './routes/_app.platform.clients'
import { Route as AppPlatformAuditLogRouteImport } from './routes/_app.platform.audit-log'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app.workspace.$workspaceId.index'
import { Route as AppWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_app.workspace.$workspaceId.settings'
import { Route as AppWorkspaceWorkspaceIdRolesRouteImport } from './routes/_app.workspace.$workspaceId.roles'
import { Route as AppWorkspaceWorkspaceIdMembersRouteImport } from './routes/_app.workspace.$workspaceId.members'
import { Route as AppWorkspaceWorkspaceIdAuditLogRouteImport } from './routes/_app.workspace.$workspaceId.audit-log'
import { Route as AppPlatformClientsSlugUsersRouteImport } from './routes/_app.platform.clients.$slug.users'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformIndexRoute = AppPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformUsersRoute = AppPlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformSettingsRoute = AppPlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformRolesRoute = AppPlatformRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformClientsRoute = AppPlatformClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformAuditLogRoute = AppPlatformAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSettingsRoute =
  AppWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdRolesRoute =
  AppWorkspaceWorkspaceIdRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdMembersRoute =
  AppWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdAuditLogRoute =
  AppWorkspaceWorkspaceIdAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppPlatformClientsSlugUsersRoute =
  AppPlatformClientsSlugUsersRouteImport.update({
    id: '/$slug/users',
    path: '/$slug/users',
    getParentRoute: () => AppPlatformClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/platform': typeof AppPlatformRouteWithChildren
  '/platform/audit-log': typeof AppPlatformAuditLogRoute
  '/platform/clients': typeof AppPlatformClientsRouteWithChildren
  '/platform/roles': typeof AppPlatformRolesRoute
  '/platform/settings': typeof AppPlatformSettingsRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/platform/': typeof AppPlatformIndexRoute
  '/workspace/$workspaceId/audit-log': typeof AppWorkspaceWorkspaceIdAuditLogRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/roles': typeof AppWorkspaceWorkspaceIdRolesRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/platform/clients/$slug/users': typeof AppPlatformClientsSlugUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/platform/audit-log': typeof AppPlatformAuditLogRoute
  '/platform/clients': typeof AppPlatformClientsRouteWithChildren
  '/platform/roles': typeof AppPlatformRolesRoute
  '/platform/settings': typeof AppPlatformSettingsRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/platform': typeof AppPlatformIndexRoute
  '/workspace/$workspaceId/audit-log': typeof AppWorkspaceWorkspaceIdAuditLogRoute
  '/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/workspace/$workspaceId/roles': typeof AppWorkspaceWorkspaceIdRolesRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/platform/clients/$slug/users': typeof AppPlatformClientsSlugUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/platform': typeof AppPlatformRouteWithChildren
  '/_app/platform/audit-log': typeof AppPlatformAuditLogRoute
  '/_app/platform/clients': typeof AppPlatformClientsRouteWithChildren
  '/_app/platform/roles': typeof AppPlatformRolesRoute
  '/_app/platform/settings': typeof AppPlatformSettingsRoute
  '/_app/platform/users': typeof AppPlatformUsersRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/platform/': typeof AppPlatformIndexRoute
  '/_app/workspace/$workspaceId/audit-log': typeof AppWorkspaceWorkspaceIdAuditLogRoute
  '/_app/workspace/$workspaceId/members': typeof AppWorkspaceWorkspaceIdMembersRoute
  '/_app/workspace/$workspaceId/roles': typeof AppWorkspaceWorkspaceIdRolesRoute
  '/_app/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/_app/platform/clients/$slug/users': typeof AppPlatformClientsSlugUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/platform'
    | '/platform/audit-log'
    | '/platform/clients'
    | '/platform/roles'
    | '/platform/settings'
    | '/platform/users'
    | '/workspace/$workspaceId'
    | '/platform/'
    | '/workspace/$workspaceId/audit-log'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/roles'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/'
    | '/platform/clients/$slug/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/platform/audit-log'
    | '/platform/clients'
    | '/platform/roles'
    | '/platform/settings'
    | '/platform/users'
    | '/platform'
    | '/workspace/$workspaceId/audit-log'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/roles'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId'
    | '/platform/clients/$slug/users'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_app/platform'
    | '/_app/platform/audit-log'
    | '/_app/platform/clients'
    | '/_app/platform/roles'
    | '/_app/platform/settings'
    | '/_app/platform/users'
    | '/_app/workspace/$workspaceId'
    | '/_app/platform/'
    | '/_app/workspace/$workspaceId/audit-log'
    | '/_app/workspace/$workspaceId/members'
    | '/_app/workspace/$workspaceId/roles'
    | '/_app/workspace/$workspaceId/settings'
    | '/_app/workspace/$workspaceId/'
    | '/_app/platform/clients/$slug/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/platform': {
      id: '/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/': {
      id: '/_app/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AppPlatformIndexRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/users': {
      id: '/_app/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AppPlatformUsersRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/settings': {
      id: '/_app/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AppPlatformSettingsRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/roles': {
      id: '/_app/platform/roles'
      path: '/roles'
      fullPath: '/platform/roles'
      preLoaderRoute: typeof AppPlatformRolesRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/clients': {
      id: '/_app/platform/clients'
      path: '/clients'
      fullPath: '/platform/clients'
      preLoaderRoute: typeof AppPlatformClientsRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/audit-log': {
      id: '/_app/platform/audit-log'
      path: '/audit-log'
      fullPath: '/platform/audit-log'
      preLoaderRoute: typeof AppPlatformAuditLogRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/settings': {
      id: '/_app/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/roles': {
      id: '/_app/workspace/$workspaceId/roles'
      path: '/roles'
      fullPath: '/workspace/$workspaceId/roles'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRolesRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/members': {
      id: '/_app/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/workspace/$workspaceId/members'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/audit-log': {
      id: '/_app/workspace/$workspaceId/audit-log'
      path: '/audit-log'
      fullPath: '/workspace/$workspaceId/audit-log'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAuditLogRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/platform/clients/$slug/users': {
      id: '/_app/platform/clients/$slug/users'
      path: '/$slug/users'
      fullPath: '/platform/clients/$slug/users'
      preLoaderRoute: typeof AppPlatformClientsSlugUsersRouteImport
      parentRoute: typeof AppPlatformClientsRoute
    }
  }
}

interface AppPlatformClientsRouteChildren {
  AppPlatformClientsSlugUsersRoute: typeof AppPlatformClientsSlugUsersRoute
}

const AppPlatformClientsRouteChildren: AppPlatformClientsRouteChildren = {
  AppPlatformClientsSlugUsersRoute: AppPlatformClientsSlugUsersRoute,
}

const AppPlatformClientsRouteWithChildren =
  AppPlatformClientsRoute._addFileChildren(AppPlatformClientsRouteChildren)

interface AppPlatformRouteChildren {
  AppPlatformAuditLogRoute: typeof AppPlatformAuditLogRoute
  AppPlatformClientsRoute: typeof AppPlatformClientsRouteWithChildren
  AppPlatformRolesRoute: typeof AppPlatformRolesRoute
  AppPlatformSettingsRoute: typeof AppPlatformSettingsRoute
  AppPlatformUsersRoute: typeof AppPlatformUsersRoute
  AppPlatformIndexRoute: typeof AppPlatformIndexRoute
}

const AppPlatformRouteChildren: AppPlatformRouteChildren = {
  AppPlatformAuditLogRoute: AppPlatformAuditLogRoute,
  AppPlatformClientsRoute: AppPlatformClientsRouteWithChildren,
  AppPlatformRolesRoute: AppPlatformRolesRoute,
  AppPlatformSettingsRoute: AppPlatformSettingsRoute,
  AppPlatformUsersRoute: AppPlatformUsersRoute,
  AppPlatformIndexRoute: AppPlatformIndexRoute,
}

const AppPlatformRouteWithChildren = AppPlatformRoute._addFileChildren(
  AppPlatformRouteChildren,
)

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdAuditLogRoute: typeof AppWorkspaceWorkspaceIdAuditLogRoute
  AppWorkspaceWorkspaceIdMembersRoute: typeof AppWorkspaceWorkspaceIdMembersRoute
  AppWorkspaceWorkspaceIdRolesRoute: typeof AppWorkspaceWorkspaceIdRolesRoute
  AppWorkspaceWorkspaceIdSettingsRoute: typeof AppWorkspaceWorkspaceIdSettingsRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdAuditLogRoute: AppWorkspaceWorkspaceIdAuditLogRoute,
    AppWorkspaceWorkspaceIdMembersRoute: AppWorkspaceWorkspaceIdMembersRoute,
    AppWorkspaceWorkspaceIdRolesRoute: AppWorkspaceWorkspaceIdRolesRoute,
    AppWorkspaceWorkspaceIdSettingsRoute: AppWorkspaceWorkspaceIdSettingsRoute,
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppPlatformRoute: typeof AppPlatformRouteWithChildren
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPlatformRoute: AppPlatformRouteWithChildren,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
