"""Worker/system job-run log (worker-system-log slice).

Records one row per background-worker invocation that did work (the
``invite_email_outbox`` batch today; future AI-scan / scheduling / queue jobs
later). Captures what ran, when, how long it took, how many items it processed,
and the outcome — so an operator has a "System / Jobs" view of worker activity
("what the worker did, how, what response, on which time").

Backend-only table: RLS enabled with no policy and no grant to ``authenticated``.
The worker + the read endpoint use the owner backend connection (which bypasses
RLS by ownership); ``authenticated`` has no access at all. The read endpoint is
gated in the app by ``platform.audit.read`` (same operator audience as the
audit log).

Idle polls are NOT recorded — a job_run is written only when a batch actually
claimed and processed at least one item, so the table reflects real work, not
the every-N-second poll heartbeat.

Revision ID: 0014
Revises: 0013
Create Date: 2026-06-06
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE job_runs (
            id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_name         text NOT NULL,
            status           text NOT NULL,
            started_at       timestamptz NOT NULL,
            finished_at      timestamptz NOT NULL,
            duration_ms      int NOT NULL,
            items_processed  int NOT NULL DEFAULT 0,
            items_succeeded  int NOT NULL DEFAULT 0,
            items_failed     int NOT NULL DEFAULT 0,
            detail           jsonb,
            created_at       timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    # Operator list order: newest run first. Matches the (started_at, id) DESC
    # cursor comparator the list service uses.
    op.execute("CREATE INDEX job_runs_started_idx ON job_runs (started_at DESC, id DESC)")
    # Per-job filtering (the operator page can scope to one job_name).
    op.execute("CREATE INDEX job_runs_job_name_idx ON job_runs (job_name, started_at DESC)")
    # Backend-only: RLS on, no policy, no authenticated grant.
    op.execute("ALTER TABLE job_runs ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS job_runs")
