// packages/api-types/src/me.ts
//
// Thin re-exports of the generated OpenAPI schemas for the `/api/me` payload
// (F.3, finding H13). The generated `components["schemas"][...]` types are the
// single source of truth — see generated/openapi.d.ts (regenerated by
// `pnpm api-types:generate`, drift-gated in CI).
//
// `PermissionKey` is a UI-only convenience alias with NO OpenAPI counterpart
// (the backend serialises permission keys as plain strings), so it stays
// hand-written here.

import type { components } from "../generated/openapi";

export type PlatformRole = components["schemas"]["PlatformRole"];
export type TenantRole = components["schemas"]["TenantRole"];

/** Permission key as defined in apps/api/src/xtrusio_api/rbac/catalog.py. */
export type PermissionKey = string;

export type PlatformContext = components["schemas"]["PlatformContext"];
export type TenantContext = components["schemas"]["TenantContext"];
export type PendingInvite = components["schemas"]["PendingInvite"];
export type MeResponse = components["schemas"]["MeResponse"];
