#!/usr/bin/env bash
# Generate .env from .env.example + live `supabase status -o env`.
# Outputs to stdout; the Makefile target redirects to .env.
#
# Requires Supabase to be running. If it isn't, exits with a clear error.
set -euo pipefail

if ! supabase status >/dev/null 2>&1; then
  echo "ERROR: Supabase is not running. Start it first with: make db-up" >&2
  exit 1
fi

# Capture supabase env output once (slow-ish call). Suppress CLI chatter that
# would otherwise contaminate the generated file.
SUPABASE_ENV=$(supabase status -o env 2>/dev/null)

extract() {
  # Pull the value of a key from the supabase env block (strips surrounding quotes).
  echo "$SUPABASE_ENV" | sed -nE "s/^${1}=\"(.*)\"\$/\1/p"
}

ANON_KEY=$(extract ANON_KEY)
SERVICE_ROLE_KEY=$(extract SERVICE_ROLE_KEY)
PUBLISHABLE_KEY=$(extract PUBLISHABLE_KEY)
SECRET_KEY=$(extract SECRET_KEY)
API_URL=$(extract API_URL)
DB_URL=$(extract DB_URL)
JWT_SECRET=$(extract JWT_SECRET)

# DB_URL is plain `postgresql://...`; FastAPI/SQLAlchemy uses `postgresql+asyncpg://...`
ASYNC_DB_URL="${DB_URL/postgresql:\/\//postgresql+asyncpg:\/\/}"

# Replace 127.0.0.1 with localhost for consistency (everything we run binds both).
API_URL_LOCAL="${API_URL//127.0.0.1/localhost}"
ASYNC_DB_URL="${ASYNC_DB_URL//127.0.0.1/localhost}"

cat <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run with \`make env-force\` to regenerate after Supabase keys rotate.
# DO NOT COMMIT — .env is gitignored.

# === Process role (required) ===
XTRUSIO_PROCESS_ROLE=api

# === Database (Supabase Postgres, managed by \`supabase start\`) ===
DATABASE_URL=${ASYNC_DB_URL}

# === Supabase API (managed by \`supabase start\`) ===
SUPABASE_URL=${API_URL_LOCAL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
# v2 token-format keys (Supabase CLI v2.x) — equivalent to anon/service_role above.
SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
SUPABASE_SECRET_KEY=${SECRET_KEY}
SUPABASE_JWT_SECRET=${JWT_SECRET}

# === Valkey (host port 63792 → xtrusio-valkey:6379 on xtrusio-net) ===
VALKEY_URL=redis://localhost:63792/0

# === Frontend (publishable/anon key only — never put secret_role in a frontend bundle) ===
VITE_API_BASE_URL=http://localhost:8000
VITE_SUPABASE_URL=${API_URL_LOCAL}
VITE_SUPABASE_ANON_KEY=${ANON_KEY}

# === Observability (filled in later plans) ===
SENTRY_DSN=
LOG_LEVEL=INFO
EOF
